export const COUNTRY_LIST = 'COUNTRY_LIST';
export const COUNTRY_LIST_FILTER = 'COUNTRY_LIST_FILTER';
export const COUNTRY_LIST_BY_NAME = 'COUNTRY_LIST_BY_NAME';
export const COUNTRY_LIST_BY_REGION = 'COUNTRY_LIST_BY_REGION';